# Generated by Django 5.0.2 on 2025-04-06 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['doctor', 'rating'], name='reviews_rev_doctor__01322d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['verified_visit'], name='reviews_rev_verifie_7d6cd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('doctor', 'user')},
        ),
    ]
