# Generated by Django 5.0.2 on 2025-04-06 12:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.CharField(choices=[('0-5', '0-5 years'), ('5-10', '5-10 years'), ('10-15', '10-15 years'), ('15+', '15+ years')], max_length=5)),
                ('bio', ckeditor.fields.RichTextField()),
                ('clinic_address', models.TextField()),
                ('clinic_city', models.CharField(max_length=100)),
                ('clinic_state', models.CharField(max_length=100)),
                ('clinic_pincode', models.CharField(max_length=6)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_days', models.CharField(max_length=200)),
                ('available_hours', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(blank=True, upload_to='doctors/profile_pics/')),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='doctors/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
