# Generated by Django 5.0.2 on 2025-04-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='icon',
            field=models.CharField(default='bi bi-heart-pulse', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(help_text='Years of experience'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specializations',
            field=models.ManyToManyField(related_name='doctors', to='doctors.specialization'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
