# Generated by Django 5.0.2 on 2025-04-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_specialization_icon_alter_doctor_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.CharField(choices=[('0-5', '0-5 years'), ('5-10', '5-10 years'), ('10-15', '10-15 years'), ('15+', '15+ years')], default='0-5', max_length=10),
        ),
    ]
